
package prociencia.views.panels;

import prociencia.logic.core.entities.Persona;
import prociencia.logic.core.entities.OcupacionEnum;
import prociencia.logic.core.util.tads.JTextFieldTad;
import prociencia.logic.core.util.tads.Observador;
import prociencia.logic.model.ControlModel;
import prociencia.views.dialogs.DialogConfirmar;

/**
 *
 * @author Klac
 */
public class PanelRegistroEstudiante extends javax.swing.JPanel {

    private final java.util.ResourceBundle RB =
            java.util.ResourceBundle.getBundle(PanelRegistroEstudiante.class.getPackage().getName()+".properties.PropertiesRegistro");
   
    private OcupacionEnum ocupacion = OcupacionEnum.ESTUDIANTE;
    private PanelValidador panelOCupacionView = new PanelCaseEstudiante(RB);
    
    public PanelRegistroEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNombre = new javax.swing.JLabel();
        jTNombres = new JTextFieldTad();
        jLabel1 = new javax.swing.JLabel();
        jTEdad = new JTextFieldTad(true);
        jSeparator2 = new javax.swing.JSeparator();
        jLabelProceso = new javax.swing.JLabel();
        jComboBoxOcupacion = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabelGuiaNombres = new javax.swing.JLabel();
        jPanelOcupacion = new javax.swing.JPanel();
        jButtonEnviar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Datos del Personales");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(51, 51, 51));
        jLabelNombre.setText("Nombre y apellidos:");

        jTNombres.setFont(jLabelNombre.getFont());
        jTNombres.setToolTipText(RB.getString("TickNomnbres")
        );
        jTNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombresActionPerformed(evt);
            }
        });
        jTNombres.addKeyListener(new KeyListenerTad());

        jLabel1.setFont(jLabelNombre.getFont());
        jLabel1.setForeground(jLabelNombre.getForeground());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Edad:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTEdad.setFont(jLabelNombre.getFont());
        jTEdad.setToolTipText(RB.getString("TickEdad"));
        jTEdad.setMinimumSize(new java.awt.Dimension(101, 20));
        jTEdad.setPreferredSize(new java.awt.Dimension(30, 20));
        jTEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEdadActionPerformed(evt);
            }
        });
        jTEdad.addKeyListener(new KeyListenerTad());

        jComboBoxOcupacion.setFont(jLabelNombre.getFont());
        jComboBoxOcupacion.setForeground(jLabelNombre.getForeground());
        jComboBoxOcupacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estudiante", "Empleado", "Otro" }));
        jComboBoxOcupacion.setToolTipText(RB.getString("TickOcupacion")
        );
        jComboBoxOcupacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxOcupacionItemStateChanged(evt);
            }
        });

        jLabel5.setFont(jLabelNombre.getFont());
        jLabel5.setForeground(jLabelNombre.getForeground());
        jLabel5.setText("Ocupación:");

        jLabelGuiaNombres.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabelGuiaNombres.setForeground(new java.awt.Color(0, 102, 255));
        jLabelGuiaNombres.setText(RB.getString("GuiaNombres"));

        jPanelOcupacion.setLayout(new java.awt.BorderLayout());

        jPanelOcupacion.add((javax.swing.JPanel)panelOCupacionView,java.awt.BorderLayout.CENTER);

        jButtonEnviar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonEnviar.setFont(jLabel2.getFont());
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEnviar.setEnabled(false);
        jButtonEnviar.setFocusPainted(false);
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanelOcupacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelGuiaNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNombres, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelGuiaNombres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanelOcupacion, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombresActionPerformed
//        jTApellidos.requestFocus();
    }//GEN-LAST:event_jTNombresActionPerformed

    private void jTEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEdadActionPerformed
        jComboBoxOcupacion.requestFocus();
    }//GEN-LAST:event_jTEdadActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        this.updateUI();
        final Persona persona = new Persona();
        persona.setNombreCompleto(jTNombres.getText());
        persona.setEdad(Integer.parseInt(jTEdad.getText()));
        persona.setTipoOcupacion(ocupacion);
        persona.setFechaRegistro(new java.sql.Date(java.util.Calendar.getInstance().getTimeInMillis()));
        if(panelOCupacionView.camposVacios()){
             panelOCupacionView.throwWarning();
//             System.err.println("Lanzamiento");
             return;
        }else{
//            System.out.println("Bummm");
             persona.setOcupacion(panelOCupacionView.getOcupacion());
        }
        registroEstudiante(persona);
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jComboBoxOcupacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxOcupacionItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
            int index = jComboBoxOcupacion.getSelectedIndex();
            jPanelOcupacion.removeAll();
                
            switch(index){
                case 0:{
                    ocupacion = OcupacionEnum.ESTUDIANTE;
                    panelOCupacionView = new PanelCaseEstudiante(RB);
                    jPanelOcupacion.add((javax.swing.JPanel) panelOCupacionView, java.awt.BorderLayout.CENTER);
                    break;
                }
                case 1:{
                    ocupacion = OcupacionEnum.EMPLEADO;
                    panelOCupacionView = new PanelCaseEmpleado(RB);
                    jPanelOcupacion.add((javax.swing.JPanel)panelOCupacionView,java.awt.BorderLayout.CENTER);
                    break;
                }case 2:{
                    ocupacion = OcupacionEnum.OTRO;
                    panelOCupacionView = new PanelCaseOtro(RB);
                    jPanelOcupacion.add((javax.swing.JPanel)panelOCupacionView, java.awt.BorderLayout.CENTER);
                    break;
                }
            }
            jPanelOcupacion.updateUI();
        }
    }//GEN-LAST:event_jComboBoxOcupacionItemStateChanged

    
    public void registroEstudiante(final Persona persona){
        final Runnable run = new Runnable(){
            @Override
            public void run(){
                ControlModel.getInstance().setPersona(persona);
                Observador.getInstance().notifyObservers(0);
                DialogConfirmar confirmar = new DialogConfirmar(PanelRegistroEstudiante.this, persona.getNombreCompleto());
                if(confirmar.getRespuesta() == 1){
                     ControlModel.getInstance().waiting();
                     Observador.getInstance().notifyObservers(1);                    
                     ControlModel.getInstance().establacerPanelActual(new PanelTest());
                }
                
            }
        };
        new Thread(run).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JComboBox jComboBoxOcupacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelGuiaNombres;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelProceso;
    private javax.swing.JPanel jPanelOcupacion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTEdad;
    private javax.swing.JTextField jTNombres;
    // End of variables declaration//GEN-END:variables

    private class KeyListenerTad extends java.awt.event.KeyAdapter{

        @Override
        public void keyReleased(java.awt.event.KeyEvent e) {
//            if(((JTextFieldTad)(jTNombres)).fieldEmply()||((JTextFieldTad)(jTApellidos)).fieldEmply()||((JTextFieldTad)(jTEdad)).fieldEmply()||
//                    ((JTextFieldTad)(jTextFieldInstitucion)).fieldEmply()){
//                jLabelProceso.setIcon(null);
//                if(!((JTextFieldTad)(jTNombres)).fieldEmply()&&((JTextFieldTad)(jTApellidos)).fieldEmply()){
//                    jLabelProceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prociencia/views/resources/bonus48x48_11.png")));
//                }else if(!((JTextFieldTad)(jTNombres)).fieldEmply()&&!((JTextFieldTad)(jTApellidos)).fieldEmply()){
//                    jLabelProceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prociencia/views/resources/bonus48x48_12.png")));
//                }
//                jButtonEnviar.setEnabled(false);
//            }else{
//                jButtonEnviar.setEnabled(true);
//                jLabelProceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prociencia/views/resources/bonus48x48_16.png")));
//            }
            
            if(((JTextFieldTad)jTNombres).fieldEmply() || ((JTextFieldTad)jTEdad).fieldEmply()){
                jLabelProceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prociencia/views/resources/bonus48x48_11.png")));
                if(!((JTextFieldTad)(jTNombres)).fieldEmply() && ((JTextFieldTad)jTEdad).fieldEmply()){
                    jLabelProceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prociencia/views/resources/bonus48x48_12.png")));
                }
                jButtonEnviar.setEnabled(false);
            }else{
                jLabelProceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prociencia/views/resources/bonus48x48_16.png")));
                jButtonEnviar.setEnabled(true);
            }
        }
        
    }
}
