/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prociencia.views.panels;

import prociencia.logic.core.entities.Persona;
import prociencia.logic.model.ControlModel;
import prociencia.logic.model.ControlModelAdministrador;

/**
 *
 * @author Klac
 */
public class PanelView extends javax.swing.JPanel {

    private final Persona person;
    private final ControlModelAdministrador logicaAdministrador = ControlModel.getInstance().getControlModelAdministrador();
    
    public PanelView(Persona person) {
        this.person = person;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButtonViewResultado = new javax.swing.JButton();
        jButtonDataPerson = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("DATOS PERSONALES Y RESULTADOS DE LA PRUEBA");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);

        jButtonViewResultado.setBackground(new java.awt.Color(204, 204, 255));
        jButtonViewResultado.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButtonViewResultado.setForeground(new java.awt.Color(102, 102, 102));
        jButtonViewResultado.setText("Resultados");
        jButtonViewResultado.setBorderPainted(false);
        jButtonViewResultado.setFocusPainted(false);

        jButtonDataPerson.setBackground(new java.awt.Color(204, 204, 255));
        jButtonDataPerson.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButtonDataPerson.setForeground(new java.awt.Color(102, 102, 102));
        jButtonDataPerson.setText("Información personal");
        jButtonDataPerson.setBorderPainted(false);
        jButtonDataPerson.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonDataPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jButtonViewResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonViewResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDataPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(357, 357, 357))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDataPerson;
    private javax.swing.JButton jButtonViewResultado;
    // End of variables declaration//GEN-END:variables
}
